name: app_frontend_clinica
description: Sistema de Gestión de Historias Clínicas con Flutter y Spring Boot
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # HTTP Client
  dio: ^5.4.0
  
  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Internationalization
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
